# Generated by Django 5.1.2 on 2024-10-10 16:17

import chatapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file',
            field=models.FileField(storage=chatapp.models.CustomS3Boto3Storage(), upload_to='aizen-uploads/'),
        ),
    ]
